### ISSUE TITLE
Missing Files in Viewer

### ISSUE THREAD

**Issue by CodedRubyChan** [Sewer56/CriFsV2Lib#1]
On your Twitter you showed that you can now extract the even encrypted files from P5R (for example "BATTLE/BOSS/...") and i wanted to extract my CPKs to have a complete file dump, but i cannot extract it. 

And i dont know if i did something wrong. I downloaded v1.0.1 

**Picture 1 from BASE.CPK**
![image](https://user-images.githubusercontent.com/40892993/202054159-0593b013-be41-4447-b488-cc891f1db6e4.png)

**Picture 2 from DE.CPK**
![image](https://user-images.githubusercontent.com/40892993/202054248-ea1f63ea-314a-44cd-8410-9143ab109c0f.png)

**Picture 3 from EN.CPK**
![image](https://user-images.githubusercontent.com/40892993/202054298-5e151987-4907-460f-901c-395cb667798a.png)

**Comment by Sewer56** [comment]
Try a backslash `\`, I didn't normalize the paths to use a common slash, so the directory uses `/` while last folder uses `\`.

**Comment by EmreXCoded** [comment]
Does not work sadly :/

**Picture from EN.CPK but Checked on BASE.CPK too**
![image](https://user-images.githubusercontent.com/40892993/202054922-8fa9a4af-7d1a-407b-82a0-1c079e0e23c6.png)

**Comment by Secre-C** [comment]
which file are you looking for? BATTLE/BOSS isn't a directory that exists in the game's files

**Comment by CodedRubyChan** [comment]
i'm very confused right now, but i think i mistook it for something. Sorry for that random Issue Post, but thanks for clarifing it ^^
Maybe i'm just too tired right now xD

**Comment by Sewer56** [comment]
Happens to the best of us.
