### ISSUE TITLE
ratio and file size field is non-existent for some CPK files

### ISSUE THREAD

**Issue by modusc896d352** [Sewer56/CriFsV2Lib#3]
title should be self-explanatory, but whatever, here goes nothing.

so, i have two cpk files (chr_fceye.cpk, chr_fctex.cpk) and i found myself in a situation where upon drag-and-dropping one of them into your tool, it does something funny, like this
![what?](https://files.catbox.moe/zttose.png)

"Ratio" field goes "NaN" everywhere, and "File Size" field is 0 just as well. this applies to every file inside the cpk btw.
and despite the tool reporting that there are dozens of files, it's followed with a slash, itself followed by the letter "b".

i must inform you that these cpks are _**not**_ empty in any way, shape, or form.

**Comment by Sewer56** [comment]
Unlikely to be investigated any time soon, I have a huge backlog. Up for grabs.

**Comment by modusc896d352** [comment]
well, i have way too much free time on my hands so i'm going to be the only one "grabbing" this one in the interim.

**Comment by Sewer56** [comment]
Note: The resources (particularly the 010 editor template) should be useful.

**Comment by Sewer56** [comment]
This might have been fixed by #5

**Comment by modusc896d352** [comment]
oh god
i wanted to look into this but motivation for doing so just slipped through, and i didn't have the mental capacity of learning C# just to fix this one issue

anyway, closing it now
